/* DOCX under templates/ must use {{placeholders}} only for variable facts—no leftover sample party/case text. */
import fs from"fs";import path from"path";import {promisify}from"util";import child_process from"child_process";import createReport from"docx-templates";const exec=promisify(child_process.exec);export const TEMPLATES_DIR=path.join(process.cwd(),"templates");export const DOCUMENTS_DIR=path.join(process.cwd(),"public","documents");export type RenderFormat="docx"|"pdf";export async function ensureDir(p:string){await fs.promises.mkdir(p,{recursive:true});}export async function templateFileExists(templateFile: string): Promise<boolean> {
  try {
    await fs.promises.access(path.join(TEMPLATES_DIR, templateFile));
    return true;
  } catch {
    return false;
  }
}

export async function renderDocxFromTemplate(templateFile:string,data:any){const templatePath=path.join(TEMPLATES_DIR,templateFile);const template=await fs.promises.readFile(templatePath);const buffer=await createReport({template,data,cmdDelimiter:["{{","}}"]});return Buffer.from(buffer);}export async function docxBufferToPdfBuffer(docxBuffer:Buffer){const tmpRoot=path.join(process.cwd(),"tmp-docx");await ensureDir(tmpRoot);const id=Math.random().toString(36).slice(2);const dir=path.join(tmpRoot,id);await ensureDir(dir);const inPath=path.join(dir,"in.docx");const outPath=path.join(dir,"in.pdf");await fs.promises.writeFile(inPath,docxBuffer);try{await exec(`soffice --headless --convert-to pdf --outdir "${dir}" "${inPath}"`);const pdf=await fs.promises.readFile(outPath);return pdf;}finally{fs.promises.rm(dir,{recursive:true,force:true}).catch(()=>{});}}export async function saveDraftBuffer(opts:{matterId:string;fileStem:string;format:RenderFormat;buf:Buffer;}){const dir=path.join(DOCUMENTS_DIR,opts.matterId);await ensureDir(dir);const now=new Date();const yyyy=String(now.getFullYear());const mm=String(now.getMonth()+1).padStart(2,"0");const dd=String(now.getDate()).padStart(2,"0");const dateTag=`${yyyy}-${mm}-${dd}`;const files=await fs.promises.readdir(dir).catch(()=>[] as string[]);const re=new RegExp(`^${opts.fileStem}_${dateTag}_v(\\d{3})\\.${opts.format}$`);const same=files.map(f=>re.test(f)?Number((f.match(re)as RegExpMatchArray)[1]):0).filter(Boolean);const next=(same.length?Math.max(...same):0)+1;const v=String(next).padStart(3,"0");const filename=`${opts.fileStem}_${dateTag}_v${v}.${opts.format}`;const fullPath=path.join(dir,filename);await fs.promises.writeFile(fullPath,opts.buf);return{fullPath,filename,relative:`/documents/${opts.matterId}/${filename}`};}